### ISSUE TITLE
MySQL-Datenbank aufsetzen mit Stammdatenrelation

### ISSUE THREAD

**Issue by MarcelVetter** [MartinWagner88/liverWeb#5]

**Comment by MarcelVetter** [comment]
![db](https://user-images.githubusercontent.com/32433031/31059475-1caf5064-a703-11e7-9238-1c2dbdd191d1.PNG)

**Comment by MarcelVetter** [comment]
SQL-Export funktioniert auch
![sql-export](https://user-images.githubusercontent.com/32433031/31059497-803a6a42-a703-11e7-9da7-bd98d62bbc9d.PNG)

**Comment by MartinWagner88** [comment]
Cool! Warum hast du neu geöffnet?
